# currently available methods: mol-rk2, ftcs, btcs, crank-nicolson
method = crank-nicolson
x_0 = 0
X = 1
t_0 = 0
T = 0.2
dx = 0.05
dt = 0.0014
num_corrections = 2 # number of corrections in the predictor-corrector scheme for implicit methods
