# currently available methods: euler, heun, midpoint, rk4, implicit_euler, trapezoidal
method = implicit_euler
h = 0.01
x_0 = 0
X = 2
y_0 = 1
num_corrections = 2 # number of corrections in the predictor-corrector scheme for implicit methods
