import matplotlib.pyplot as plt
import subprocess
import os

def loadSettings(file_name):
    settings = {}

    with open(file_name, "r") as file:
        for line in file:
            if not line.strip() or line[0] == '#':
                continue
        
            setting = line.split("=")
            settings[setting[0].strip()] = setting[1].strip()

    return settings

def readPoints(file_name):
    x = []
    y = []
    
    with open(file_name, "r") as file:
        for line in file:
            if not line.strip():
                continue
            
            p_x, p_y = map(float, line.strip().split(","))
            
            x.append(p_x)
            y.append(p_y)
    
    return x, y

method_names = {"euler": "Euler", "heun": "Heun", "midpoint": "Ponto médio", "rk4": "RK4", "implicit_euler": "Euler regressivo", "trapezoidal": "Trapezoidal"}

subprocess.run(["tp1-calculator.exe"])
settings_file_name = "tp1-settings.ini"
settings = loadSettings(settings_file_name)

x_res, y_res = readPoints("results.txt")
x_sol, y_sol = readPoints("solution.txt")
x_dif, e_dif = readPoints("differences.txt")

plt.figure()

plt.subplot(2, 1, 1)
plt.plot(x_res, y_res, marker='o', label=f"{method_names[settings['method']]}")
plt.plot(x_sol, y_sol, linestyle='--', label="Exata")
plt.title(rf"Solução vs Aproximação ($h = {settings['h']}$)")
plt.legend()
plt.grid()

plt.subplot(2, 1, 2)
plt.plot(x_dif, e_dif, marker='o', label="Erro")
plt.yscale('log')
plt.xlabel("x")
plt.ylabel("Erro")
plt.grid()
plt.legend()

plt.show()

# removing temporary files generated by calculator.cpp
for file in ["results.txt", "solution.txt", "differences.txt"]:
    try:
        os.remove(file)
    except FileNotFoundError:
        pass
