import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import subprocess
import os

def loadSettings(file_name):
    settings = {}

    with open(file_name, "r") as file:
        for line in file:
            if not line.strip() or line[0] == '#':
                continue
        
            setting = line.split("=")
            settings[setting[0].strip()] = setting[1].strip()

    return settings

def readPoints(file_name):
    t = []
    x = []
    u = []
    
    with open(file_name, "r") as file:
        for line in file:
            if not line.strip():
                continue
            
            p_x, p_t, p_u = map(float, line.strip().split(","))
            
            t.append(p_t)
            x.append(p_x)
            u.append(p_u)
    
    return t, x, u

method_names = {"mol-rk2": "Método das linhas + Runge-Kutta de segunda ordem", "ftcs": "Método das diferenças progressivas", "btcs": "Método das diferenças regressivas", "crank-nicolson": "Método de Crank-Nicolson"}

subprocess.run(["calculator.exe"])
settings_file_name = "settings.ini"
settings = loadSettings(settings_file_name)

t_res, x_res, u_res = readPoints("results.txt")
t_sol, x_sol, u_sol = readPoints("solution.txt")
t_dif, x_dif, e_dif = readPoints("differences.txt")

plt.figure(figsize=(10, 8))

plt.subplot(2, 1, 1)

scatter = plt.scatter(
    t_res,
    x_res,
    c=u_res,
    cmap='coolwarm'
)

plt.colorbar(scatter, label="u(x,t)")

plt.title(rf"{method_names[settings['method']]} ($\Delta t = {settings['dt']}, \Delta x = {settings['dx']}$)")
plt.xlabel("x")
plt.ylabel("t")

plt.subplot(2, 1, 2)

scatter_error = plt.scatter(
    t_dif,
    x_dif,
    c=e_dif,
    cmap='gray',
    norm=LogNorm()
)

plt.colorbar(scatter_error, label="Erro")

plt.title("Erro absoluto")
plt.xlabel("x")
plt.ylabel("t")

plt.tight_layout()
plt.show()

# removing temporary files generated by calculator.cpp
for file in ["results.txt", "solution.txt", "differences.txt"]:
    try:
        os.remove(file)
    except FileNotFoundError:
        pass
